# Generated by Django 4.0 on 2021-12-19 03:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 3, 23, 27, 710355, tzinfo=utc), editable=False),
        ),
    ]
