# Generated by Django 4.0 on 2021-12-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_food_options_food_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
