# Generated by Django 4.0.1 on 2022-01-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_category_slug_remove_food_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
