# Generated by Django 4.0.1 on 2022-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_delete_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('foods', models.ManyToManyField(null=True, related_name='foods', to='backend.Food')),
            ],
        ),
    ]
