# Generated by Django 4.0.1 on 2022-01-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
        migrations.CreateModel(
            name='OrderedFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.food')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='foods',
            field=models.ManyToManyField(null=True, related_name='Ordered_Foods', to='backend.OrderedFoods'),
        ),
    ]
