# Generated by Django 4.0.1 on 2022-01-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_orders_total_price_orderedfoods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfoods',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='backend.food'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='foods',
            field=models.ManyToManyField(null=True, related_name='ordered_foods', to='backend.OrderedFoods'),
        ),
    ]
