# Generated by Django 4.0.1 on 2022-01-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_orderedfoods_food_alter_orders_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfoods',
            name='date_added',
        ),
        migrations.AddField(
            model_name='orders',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
