# Generated by Django 4.0.1 on 2022-01-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_orderedfoods_date_added_orders_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='foods',
            field=models.ManyToManyField(related_name='ordered_foods', to='backend.OrderedFoods'),
        ),
    ]
