# Generated by Django 4.0.1 on 2022-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_orders_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='foods',
            field=models.ManyToManyField(to='backend.OrderedFoods'),
        ),
    ]
