# Generated by Django 4.0.1 on 2022-01-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
