# Generated by Django 4.0.1 on 2022-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_orderedfoods_food_orderedfoods_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfoods',
            name='customer',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
