# Generated by Django 4.0.1 on 2022-01-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_orderedfoods_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfoods',
            name='quantity',
        ),
    ]
