# Generated by Django 4.0 on 2022-01-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0019_remove_orderedfoods_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='orderedfoods',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterField(
            model_name='orderedfoods',
            name='food',
            field=models.ManyToManyField(related_name='food', to='backend.Food'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
