# Generated by Django 4.0 on 2022-01-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_orderedfoods_customer_orderedfoods_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedFoods',
            new_name='OrderItem',
        ),
    ]
