# Generated by Django 4.0 on 2022-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_orderedfoods_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
