# Generated by Django 4.0 on 2022-01-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
